version: "3.8"
services:

  name:
    image: tp1
    ports:
      - "8000"
    networks:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure