version: "3.3"
services:
  tp2:
    build:
      context: .
      dockerfile: Dockerfile
    image: tp2
    ports:
      - "8000:8000"
    networks:
      node_net:
        ipv4_address: 172.16.238.2

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/16"
