version: "3.3"
services:
  db:
    image: postgres
    env_file:
      - database.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  database-data:

networks:
  node_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.0.0/16"
